### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by hruchka** [hruchka/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by iLoveJesusChrist** [comment]
<h2>Résumé</h2>
<p>&mdash; For almost ninety years I’ve walked among my kind, and yours… all the time thinking I was complete in myself, not realizing what I was seeking. And not finding anything, because you weren’t alive yet. You are the only one who has ever touched my heart. It will always be yours…
</p>

**Comment by hruchka** [comment]
God bless you!
